### ISSUE TITLE
Store actions getting trashed

### ISSUE THREAD

**Issue by kaw2k** [willowtreeapps/tuxxor#1]
https://github.com/willowtreeapps/tuxxor/blob/master/tuxxor.js#L86

The `flattenDispatches` method is not playing nicely. Removing line 86 seems to fix it, not sure what else this method is meant to do. `invertObjects` is already flattening out arrays so maybe we don't need `flattenDispatches`.

**Comment by tlegard** [comment]
running `invertObjects({login: ["LOGIN", "LOGOUT"]})` did not produce the expected output. removing it in favor `flattenDispatches` since `flattenDispatches` also inverts.
